version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6-jessie
    steps:
      - checkout
      - run:
          name: Install required packages
          command: |
            sudo pip3 install pyflakes
      - run:
          name: Check syntax
          command: |
            pyflakes src/*.py
  build:
    docker:
      - image: circleci/python:3.6-jessie
    steps:
      - checkout
      - run:
          name: Deploy bot
          command: |
            scp -o StrictHostKeyChecking=no -r requirements.txt ubuntu@34.255.3.221:~
            scp -o StrictHostKeyChecking=no -r src/ ubuntu@34.255.3.221:~/bot
            ssh ubuntu@34.255.3.221 'auto_deploy'

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master